apiVersion: v1
kind: Service
metadata:
  name: wil-service
  labels:
    app: wil
spec:
  selector:
    app: wil
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  type: ClusterIP
